name: YAM Boat Slot Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Run slot monitor
        env:
          YAM_USERNAME: ${{ secrets.YAM_USERNAME }}
          YAM_PASSWORD: ${{ secrets.YAM_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python -m app.main monitor --interval 30 --days 14

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add app/data/all_slots.json app/data/previous_slots.json app/data/notified_slots.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update slot data [skip ci]" && git push)
